Just trying to understand / implement paper 1 stuffs

So how shall we construct eigengame?

Input: 
* Data $ R^{n x d} $ where n = # data points , d = feature space

Output:
* Return principle components 


### Algorithm 1:
* maximum error tolerance
* init vector $ v^{0}_{i} $ - sample from unit sphere
* learned approx parents
* learning rate
* set $ v_{i} \rightarrow v^{0}_{i} $
* compute $ t_{i} $ - number of steps to run for. Dont get this calc yet
* for some number of steps DO:
    * Calc Reward
    * Calc penalty
    * Compute $ \Delta_{v_{i}} $
    * Compute the reimann projection
    * Compute update $ v_{i}^{'} $
    * Renorm

In [3]:
import numpy as np

def sample_spherical(npoints, ndim=3):
    vec = np.random.randn(ndim, npoints)
    vec /= np.linalg.norm(vec, axis=0)
    return vec


In [177]:
def update_eigenvector(X: np.array, parents: list[np.array], d: int) -> tuple:
    """
    Follow Algorithm 1
    """
    v_i = sample_spherical(1, d)  # want d x 1
    lr = 0.01
    t_i = 10000  # TEMP
    # precompute rewards upfront for each vector of parents
    rewards_j = [np.matmul(X, v_j) for v_j in parents]
    for i in range(t_i):
        reward_i = np.matmul(X, v_i)  # n x 1

        penalty = np.zeros((reward_i.shape))
        for r_j in rewards_j:
            p = float(np.dot(reward_i.T, r_j) / np.dot(r_j.T, r_j))
            penalty += p * r_j

        delta_vi = 2.0 * np.matmul(X.T, (reward_i - penalty))

        reimann_projection = delta_vi - float(np.dot(delta_vi.T, v_i)) * v_i

        v_prime = v_i + lr * reimann_projection

        v_i = v_prime / np.linalg.norm(v_prime, axis=0)

    return v_i, parents

In [178]:
X = np.random.random((10,3))
#parents = [sample_spherical(1,3)]

In [179]:
parents = []

In [180]:
v_new , parents = update_eigenvector(X,parents,d=3)

One quick and easy test to see if this is working is to see if the new vector is orthogonal to parent

In [181]:
v_new

array([[-0.60254041],
       [-0.61193931],
       [-0.51232347]])

In [182]:
parents = [v_new]

In [183]:
v_new_2 , parents = update_eigenvector(X,parents,d=3)

In [184]:
np.dot(v_new.T,v_new_2)

array([[-3.88578059e-15]])

In [185]:
v_new_2

array([[ 0.72367048],
       [-0.14824366],
       [-0.67403624]])

In [186]:
parents = [v_new,v_new_2]

In [187]:
v_new_3 , parents = update_eigenvector(X,parents,d=3)

In [188]:
from numpy.linalg import eig
from sklearn.decomposition import PCA

In [149]:
pca = PCA(n_components=3)

In [150]:
pca.fit(X)

PCA(n_components=3)

In [151]:
pca.components_

array([[ 0.62276282, -0.74699233,  0.2327422 ],
       [-0.64244351, -0.31842047,  0.69704716],
       [ 0.446579  ,  0.58361877,  0.67820081]])

In [152]:
pc1,pc2,pc3 = pca.components_

In [159]:
np.dot(pc3,v_new_2)

array([-0.03758203])

In [147]:
pc1

array([ 0.62276282, -0.74699233,  0.2327422 ])

In [189]:
v_new

array([[-0.60254041],
       [-0.61193931],
       [-0.51232347]])

In [190]:
v_new_2

array([[ 0.72367048],
       [-0.14824366],
       [-0.67403624]])

In [191]:
v_new_3

array([[-0.33652056],
       [ 0.77688744],
       [-0.53216521]])

In [196]:
np.dot(v_new_3.T,v_new_2)

array([[-5.32907052e-15]])

In [128]:
np.dot(v_new_2.flatten(),pca.components_[0])

0.9991949739712095

In [197]:
from sklearn.datasets import load_digits

In [199]:
digits = load_digits()

In [203]:
digits[0]

KeyError: 0